### ISSUE TITLE
Inference time of the Quantized model 

### ISSUE THREAD

**Issue by abhigoku10** [sony/model_optimization#365]
### Issue Type

Documentation

### Source

pip (model-compression-toolkit)

### MCT Version

1.4.0

### OS Platform and Distribution

Linux Ubuntu18

### Python version

3.10

### Describe the issue

```shell
Can you please provide the inference time  of the quantized model for references
```

### Code to reproduce the issue

```shell
Can you please provide the inference time  of the quantized model for references
```

**Comment by elad-c** [comment]
The model inference time after MCT is expected to roughly remain the same as the inference time of the model before MCT, and may even be slightly higher. The reason is that the MCT generates a float model with fake quantization nodes, which simulates the accuracy of a a fully quantized model. Achieving the model inference acceleration (and parameters size compression) requires further conversion to integer weights and activations. This is typically done at the deployment phase to the specific inference platform.
