### ISSUE TITLE
Faster quantization params search: keep it on GPU

### ISSUE THREAD

**Issue by mikeseven** [sony/model_optimization#798]
### Issue Type

Performance

### Source

source

### MCT Version

main

### OS Platform and Distribution

ubuntu 20.04, pytorch 2, cuda 12

### Python version

3.11

### Describe the issue

```shell
MCT is very slow even on high-end multi-core, multi-GPU servers with tons of memory.

The culprit is evaluating quantization parameters after calibration. This phase runs on numpy and every tensor must first be moved from GPU to CPU.

Tensors and quantization params search should be kept on GPU as much as possible.
```

### Expected behaviour

```shell
huge speed improvements!
```

### Code to reproduce the issue

```shell
...
```

**Comment by ofirgo** [comment]
Hi @mikeseven,

This is a design decision to execute the param search with numpy, to avoid code duplication between frameworks.
From our experience, this doesn't cause a significant slow-down (several minutes tops in some scenarios), so we prefer the code reuse rather than re-implementing the entire logic per framework. 

If you encountered a significant slowdown in a certain scenario please let us know the specific case so we can debug it and see what can be done to improve the execution.
